In [2]:
from __future__ import print_function
import torch

tensor([[1.3105e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 6.4460e-44],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])

In [3]:
x = torch.empty(5,3)
x

tensor([[1.3105e-35, 0.0000e+00, 1.5975e-43],
        [1.3873e-43, 1.4574e-43, 6.4460e-44],
        [1.4153e-43, 1.5274e-43, 1.5695e-43],
        [1.6255e-43, 1.6956e-43, 1.5274e-43],
        [1.5695e-43, 2.2856e+20, 5.0948e-14]])

In [5]:
#Construct a randomly initialized matrix:
x = torch.rand(5,3)
x

tensor([[0.1817, 0.5050, 0.8282],
        [0.3897, 0.6792, 0.3658],
        [0.9782, 0.2353, 0.2152],
        [0.5091, 0.3078, 0.7201],
        [0.1837, 0.3954, 0.8834]])

In [7]:
#Construct a matrix filled zeros and of dtype long:
x = torch.zeros(5,3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [9]:
#Construct a tensor directly from data:
x = torch.tensor([5,3])
x

tensor([5, 3])

In [10]:
x = x.new_ones([5,3], dtype = torch.double)   #
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [12]:
x=torch.randn_like(x, dtype=torch.float)
x

tensor([[ 0.5058, -2.1677, -0.2924],
        [-0.7803,  0.1318,  0.0054],
        [ 1.0421,  0.3767, -0.3475],
        [-0.8158, -0.9442,  1.2324],
        [ 1.4268,  0.2172, -0.9948]])

In [13]:
print(x.size())

torch.Size([5, 3])
