In [40]:
from __future__ import print_function
import torch

In [2]:
# buat dataset
x = torch.tensor([5,5])
y = torch.tensor([10,20])


In [3]:
# tampilkan data x
x

tensor([5, 5])

In [4]:
# tampilkan data y
y 

tensor([10, 20])

In [6]:
# jumlahkan kedua data x dan y
Add = torch.add(x,y)
print(Add)

tensor([15, 25])


In [7]:
# penjumlahan dengan cara lain dapat dilakukan sbg:
Add = x + y
print(Add)

tensor([15, 25])


In [30]:
# membuat output tensor sebagai argumen
# misalkan kita mempunyai tensor 
x = torch.tensor([[5,5],[5,5]])         # membuat tensor 2D
y = torch.tensor([[10,10],[20,20]])     # membuat tensor 2D

result = torch.empty([2,2])
ADD = torch.add(x,y, out = result)
print(ADD)

tensor([[15., 15.],
        [25., 25.]])


In [22]:
# tambahan -> teknik penjumlahan pada tensor

In [29]:
y.add_(x)
print(y)

tensor([[15, 15],
        [25, 25]])


In [31]:
x.add_(y)
print(x)

tensor([[15, 15],
        [25, 25]])


In [34]:
# You can use standard NumPy-like indexing with all bells and whistles!
print(x[:,0]) # mengambil semua angka pada kolom pertama

tensor([15, 25])


In [35]:
# You can use standard NumPy-like indexing with all bells and whistles!
print(x[:,1]) # mengambil semua angka pada kolom pertama

tensor([15, 25])


In [36]:
# You can use standard NumPy-like indexing with all bells and whistles!
print(x[0,:]) # mengambil semua angka pada baris pertama

tensor([15, 15])


In [39]:
# You can use standard NumPy-like indexing with all bells and whistles!
print(x[1,:]) # mengambil semua angka pada baris kedua

tensor([25, 25])


In [44]:
# Resizing: If you want to resize/reshape tensor, you can use torch.view:
x = torch.rand(4,4)
y = x.view(16)
z = x.view(-1,8)


In [45]:
# tampilkan x
x

tensor([[0.4008, 0.8621, 0.5250, 0.1043],
        [0.6517, 0.8874, 0.4473, 0.3673],
        [0.3289, 0.9855, 0.8306, 0.4093],
        [0.6519, 0.9419, 0.0055, 0.8807]])

In [46]:
# tampilkan y
y

tensor([0.4008, 0.8621, 0.5250, 0.1043, 0.6517, 0.8874, 0.4473, 0.3673, 0.3289,
        0.9855, 0.8306, 0.4093, 0.6519, 0.9419, 0.0055, 0.8807])

In [47]:
# tampilkan z
z

tensor([[0.4008, 0.8621, 0.5250, 0.1043, 0.6517, 0.8874, 0.4473, 0.3673],
        [0.3289, 0.9855, 0.8306, 0.4093, 0.6519, 0.9419, 0.0055, 0.8807]])

In [48]:
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [53]:
# if you have a one element tensor, use .item() to get the value as a Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.2509])
-0.2509113848209381
